package uz.everbest.requestmanagement.domain.enums;

public enum MessageText {

    GREETING,
    RUSSIAN,
    UZBEK,

    BUTTON_SELECT_LANGUAGE,
    BUTTON_REGISTRATION,
    BUTTON_SHARE_CONTACT,
    BUTTON_LOGIN,
    BUTTON_CANCEL,
    BUTTON_DELETE,
    BUTTON_MAIN_MENU,
    YES,
    NO,

    SUCCESSFULLY_REGISTRATED,
    SUCCESSFULLY_LOGGED_IN,
    YOU_ARE_NOT_LOGGED_IN,
    YOU_ARE_ALREADY_LOGGED_IN,
    WRONG_PASSWORD,

    COMMAND_COMPLETED,
    COMMAND_CANCELLED,

    OPERATION_CONFIRMATION,
    MAIN_MENU,
    INFORMATIONS,

    INFO_NAME,
    INFO_PHONE,
    INFO_ROLE,
    INFO_PASSWORD,

    INFO_COMPANY_NAME,
    INFO_COMPANY_INN,

    REQUEST_WORKER_NAME,
    REQUEST_PHONE,
    REQUEST_ROLE,
    REQUEST_PASSWORD,

    REQUEST_COMPANY_NAME,
    REQUEST_COMPANY_INN,
    COMPANY_REGISTRATED_DATE,
    COMPANY_REGISTRATED_BY,
    COMPANY_THSHT,
    COMPANY_DBIBT,
    COMPANY_IFUT,
    COMPANY_USTAV_FONDI,
    COMPANY_ADDRESS,
    COMPANY_PHONE,
    COMPANY_EMAIL,
    COMPANY_LEADER,
    COMPANY_FOUNDERS,
    COMPANY_ACCOUNT_NUMBER,
    COMPANY_BANK_CODE,
    COMPANY_BANK_NAME,

    REQUEST_CLIENT_COMPANIES,

    REQUEST_CHOOSE_PROFILE,
    REQUEST_MESSAGE_BODY,
    REQUEST_UPLOAD_DOCUMENT,

    BUTTON_WORKERS,
    BUTTON_WORKERS_ADD,
    BUTTON_WORKERS_LIST,

    BUTTON_COMPANIES,
    BUTTON_COMPANIES_ADD,
    BUTTON_COMPANIES_LIST,

    BUTTON_CLIENTS,
    BUTTON_CLIENTS_ADD,
    BUTTON_CLIENTS_LIST,
    BUTTON_CLIENTS_FINISH,

    NOT_FOUND_WORKERS,
    NOT_FOUND_COMPANIES,
    NOT_FOUND_CLIENTS,

    BUTTON_ADD_REQUEST,
    BUTTON_ADD_MEDIA,
    BUTTON_SEND_REQUEST

}
